name: Deploy Backend to Azure Web Apps (Service Principal)  
  
on:  
  push:  
    branches:  
      - main  
  
env:  
  PYTHON_VERSION: '3.11'  
  
jobs:  
  build-and-deploy-backend:  
    name: Build & Deploy Backend (FastAPI / Python)  
    runs-on: ubuntu-latest  
    defaults:  
      run:  
        working-directory: .  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  
  
      - name: Set up Python ${{ env.PYTHON_VERSION }}  
        uses: actions/setup-python@v5  
        with:  
          python-version: ${{ env.PYTHON_VERSION }}  
  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install -r backend/requirements.txt
  
      - name: Azure Login  
        uses: azure/login@v2  
        with:  
          creds: ${{ secrets.AZURE_CREDENTIALS }}  
  
      - name: Deploy to Azure Web App (Backend)  
        uses: azure/webapps-deploy@v3  
        with:  
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_BACKEND }}  
          package: ./backend  
          startup-command: "uvicorn backend.main:app --host 0.0.0.0 --port 8000"  
