name: Deploy Frontend to Azure Web Apps (Service Principal)  
on:    
  push:      
    branches:        
      - main  
env:    
  NODE_VERSION: '22'  
jobs:    
  build-and-deploy-frontend:      
    name: Deploy Frontend (Static HTML/CSS/JS)      
    runs-on: ubuntu-latest      
    defaults:        
      run:          
        working-directory: ./frontend      
    steps:        
      - name: Checkout code          
        uses: actions/checkout@v4  
  
      # Install dependencies only if you need serve or linting; otherwise, you can remove these two steps.        
      - name: Set up Node.js ${{ env.NODE_VERSION }}          
        uses: actions/setup-node@v4          
        with:            
          node-version: ${{ env.NODE_VERSION }}  
  
      - name: Install dependencies          
        run: npm install  
  
      - name: Azure Login          
        uses: azure/login@v2          
        with:            
          creds: ${{ secrets.AZURE_CREDENTIALS }}  
  
      - name: Deploy to Azure Web App (Frontend)          
        uses: azure/webapps-deploy@v3          
        with:            
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_FRONTEND }}            
          package: ./frontend  
